version: "3.9"
services:
  backend:
    image: node:20-slim
    working_dir: /app
    container_name: localmenu-backend-dev
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev --name init || true && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - localmenu-net
  postgres:
    image: postgres:16-alpine
    container_name: localmenu-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: localmenu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    networks:
      - localmenu-net
networks:
  localmenu-net:
    driver: bridge
volumes:
  pg_data_dev: