FROM node:20-slim

WORKDIR /app

# Copia apenas os arquivos de dependências para instalar primeiro
COPY package.json package-lock.json* ./
RUN npm install

# Copia o restante do código
COPY tsconfig.json tsconfig.build.json nest-cli.json ./
COPY prisma ./prisma
COPY src ./src

# Gera o Prisma Client
RUN npx prisma generate

EXPOSE 3000

# Comando para rodar em modo desenvolvimento (hot reload)
CMD ["npm", "run", "start:dev"]